application: dropboxplayer
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static
- url: /css
  static_dir: static
- url: /js
  static_dir: static

- url: .*
  script: main.py
